### ISSUE TITLE
PDF files not displaying

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri-server#34]
PDF files are no longer displaying. I am experiencing this problem at least in channel with token `lirub-laruk`. Every last level folder has a HTML content and 2 PDF files.  Earlier the problem was with HTML content which has been fixed in #24 .
Have not tested with other channels.

**Environment**
Ubuntu 18.04.2
kolibri-server 0.3.2
kolibri 0.12.8

**Comment by ivanistheone** [comment]
Hi @intelliant01 could you post a screenshot and any extra info from the js console and/or errors from the network tab.


I can confirm that it's not a content issue, since the channel PDFs load fine on this online demo server (older version of Kolibri): 
http://35.227.71.104/learn/#/topics/c/cee4d15f8621468c8cfa5e621fb4d1ba

**Comment by intelliant01** [comment]
Hi @ivanistheone, Sorry this was my bad test environment with swapped content folders. PDFs are displaying fine. Hence closing.
