### ISSUE TITLE
unlink: ERR wrong number of arguments for 'unlink' 

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-server#63]
During installation on top of an unclean system. Suspecting something related to the only occurrence of unlink:

```
kolibri_server_setup.py
99:        delete = ["xargs", "redis-cli", "-n", arg[0], "unlink"]
```

apt output:

```
Apr 15 14:05:59 topdatamat runuser[18094]: pam_unix(runuser:session): session opened for user kolibri by (uid=0)
Apr 15 14:06:00 topdatamat kolibri-server[18060]: WARNING  Options file /tmp/test/options.ini has been updated; server restart is required before change will take effect.
Apr 15 14:06:00 topdatamat kolibri-server[18060]: WARNING  Options file /tmp/test/options.ini has been updated; server restart is required before change will take effect.
Apr 15 14:06:00 topdatamat kolibri-server[18060]: 186
Apr 15 14:06:00 topdatamat kolibri-server[18060]: 2
Apr 15 14:06:00 topdatamat kolibri-server[18060]: ERR wrong number of arguments for 'unlink' command
Apr 15 14:06:00 topdatamat kolibri-server[18060]: ERR wrong number of arguments for 'unlink' command
Apr 15 14:06:00 topdatamat kolibri-server[18060]: ERR wrong number of arguments for 'unlink' command
Apr 15 14:06:00 topdatamat kolibri-server[18060]: 27
Apr 15 14:06:00 topdatamat runuser[18094]: pam_unix(runuser:session): session closed for user kolibri
Apr 15 14:06:00 topdatamat kolibri-server[18060]: debconf: DbDriver "passwords" warning: could not open /var/cache/debconf/passwords.dat: Permission denied
Apr 15 14:06:01 topdatamat kolibri-server[18060]: Job for nginx.service failed because the control process exited with error code.
Apr 15 14:06:01 topdatamat kolibri-server[18060]: See "systemctl status nginx.service" and "journalctl -xe" for details.
Apr 15 14:06:01 topdatamat runuser[18161]: pam_unix(runuser:session): session opened for user kolibri by (uid=0)
Apr 15 14:06:01 topdatamat runuser[18161]: pam_unix(runuser:session): session closed for user kolibri
Apr 15 14:06:01 topdatamat kolibri-server[18060]: [uWSGI] getting INI configuration from /etc/kolibri/dist/uwsgi.ini
Apr 15 14:06:01 topdatamat kolibri-server[18060]: Job for nginx.service failed because the control process exited with error code.
Apr 15 14:06:01 topdatamat kolibri-server[18060]: See "systemctl status nginx.service" and "journalctl -xe" for details.
```

**Comment by intelliant01** [comment]
Tested on `Ubuntu 18.04` with `kolibri-server 0.3.8~beta2` + `kolibri 0.14.b16` + `redis 4.0.9`.
Tested on `Ubuntu 20.04` with `kolibri-server 0.3.8~beta2` + `kolibri 0.14.b16` + `redis 5.0.7`.

The `unlink errors` are present and visible during `kolibri-server` start.

Additional info: No max-memory setting has been done for redis as even setting at 50% of system memory breaks Kolibri functionality and simultaneously OOM related errors are visible in kolibri logs.

Does this qualify to reopen this issue?

**Comment by jredrejo** [comment]
I imagine you created the kolibri-server package because [the fix closing this issue](https://github.com/learningequality/kolibri-server/pull/67) has not been released in any kolibri-server package yet. 

If the unlink problem persists, yes, reopen it, with the instructions to reproduce it because I can't reproduce it anymore if the correct version of redis is installed. It works fine in Ubuntu 18.04 and 

In Ubuntu 20.04:

```
$ dpkg -l redis-server
Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre         Versión      Arquitectura Descripción
+++-==============-============-============-====================================================
ii  redis-server   5:5.0.7-2    amd64        Persistent key-value database with network interface
```

In Raspbian:
```
pi@raspberrypi:~ $ dpkg -l redis-server
Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre         Versión           Arquitectura Descripción
+++-==============-=================-============-====================================================
ii  redis-server   5:5.0.3-4+deb10u2 armhf        Persistent key-value database with network interface
```


For the max-memory setting, don't reopen this issue. That's being worked in another PR because this is related to the new features added in kolibri 0.14. Current kolibri versions leave that setting to the management of the computer sysadmin. Actually, it's a task that should be taken by the admin of the system, like taking care of the hard disk space. I am not sure kolibri-server should modify it, but in case it will, it will have to respect any setting the user has previously done.

**Comment by intelliant01** [comment]
I have installed the `kolibri-server` beta package available herein - https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed/+packages

I see these messages whenever I execute `systemctl start kolibri-server` . Do keep `journalctl -f -u kolibri-server` running in another terminal otherwise it is easy to miss the 'unlink' notification.

`max-memory` information was just additional. Now understood that it is unrelated to this issue.

BTW, I can't reopen the issue.

**Comment by jredrejo** [comment]
ok, no  need to reopen it. The package you installed does not have the fixes applied. A new package version will be uploaded at the end of this week or beginning of the next one.
Sorry for the noise
